project_id = "sqsoeyvwtgkevkhpwndj"

[functions.generate-workout]
verify_jwt = true

[functions.refine-workout]
verify_jwt = true

[functions.generate-cardio-plan]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.suggest-challenge]
verify_jwt = true
