project_id = "sqsoeyvwtgkevkhpwndj"

[functions.generate-workout]
verify_jwt = true

[functions.refine-workout]
verify_jwt = true

[functions.generate-cardio-plan]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.suggest-challenge]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.match-pool-challenges]
verify_jwt = false

[functions.admin-stats]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.generate-wod]
verify_jwt = false
